driver_app/driver_app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from two_factor.urls import urlpatterns as tf_urls

# Project urls, the path to the two_factor authentication app views is included
# the media url and root for storing user pictures is also defined
urlpatterns = [
    path('', include('map.urls')),
    path(r'', include(tf_urls)),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

driver_app/map/urls.py
from django.urls import path

from . import views
from two_factor.urls import urlpatterns as tf_urls
from django.conf.urls import include


app_name = 'map'
# urls to each of the app's views, as needed
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_id>/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('book/<int:user_id>/', views.book, name='book'),
    path('complete/', views.complete, name='complete'),
    path('update/', views.update_coords, name='update_coords'),

]

driver_app/map/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


# https://stackoverflow.com/questions/34239877/django-save-user-uploads-in-seperate-folders
# define the directory path for each file upload by user
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


# model to provide extra information for auth User model
class UserInfo(models.Model):
    # refers to only one user per UserInfo
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # image for the User's profile picture
    image = models.FileField(upload_to=user_directory_path, blank=True)
    # biography for the user's profile page
    bio = models.CharField(max_length=1000, default='')
    # boolean for if the created user is a driver or not
    is_driver = models.BooleanField()
    # stores the latitude and longitude of user when they book to be picked up or are a driver
    cur_lat = models.DecimalField(max_digits=9, decimal_places=6, default=0)
    cur_long = models.DecimalField(max_digits=9, decimal_places=6, default=0)
    # used for tracking the driver that a user wants to be picked up by
    driver_id = models.IntegerField(default=0)

    def __str__(self):
        return self.bio


# model for the reviews that each driver may have on their profile
class Review(models.Model):
    # each user may have multiple reviews
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # the username of the other user that writes the review
    author = models.CharField(max_length=50)
    # a 1 - 5 rating of the driver
    rating = models.IntegerField(default=1, validators=[MaxValueValidator(5), MinValueValidator(1)])
    # text for what the user thought of the driver
    review_text = models.CharField(max_length=500)

    def __str__(self):
        return self.review_text

driver_app/map/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import UserInfo


# form to show up on the register page to get information to enter a new user and userinfo
class SignUpForm(forms.Form):
    email = forms.EmailField(max_length=200, help_text='\n')
    user_name = forms.CharField(max_length=50, help_text='\n')
    first_name = forms.CharField(max_length=20, help_text='\n')
    last_name = forms.CharField(max_length=20, help_text='\n')
    # choice filed to define whether the user is a driver or a non driver
    is_driver = forms.ChoiceField(label='Are you a user or a driver?', choices=(('False','User'),('True','Driver')), help_text='\n')
    # 2 password fields to ensure that the user has entered the password correctly
    password = forms.CharField(widget=forms.PasswordInput(), max_length=50, label='Password', help_text='\n')
    password2 = forms.CharField(widget=forms.PasswordInput(), max_length=50, label='Reenter Password')

    # checks if the email already exists in the database
    def clean_email(self):
        email = self.cleaned_data['email']
        # if the email exists, raise a validation error
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists")
        # return the email if its valid
        return email

    # checks if the entered username already exists in the database
    def clean_user_name(self):
        username = self.cleaned_data['user_name']
        # if the username exists, raise a validation error
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Username already exists")
        # return the username if its valid
        return username

    # checks if the passwords match and if they are complex enough
    # partially retrieved from https://stackoverflow.com/questions/7948750/custom-form-validation
    def clean(self):
        form_data = self.cleaned_data
        if form_data['password'] != form_data['password2']:
            self._errors["password"] = ["Password does not match"]
            del form_data['password']
        return form_data

    # meta information to define the form fields
    class Meta:
        model = User
        fields = ('email', 'user_name', 'first_name', 'last_name', 'is_driver', 'password', 'password2', )

driver_app/map/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.conf import settings
from django.urls import reverse
from django.views import generic
from django import forms
from django.core.files.storage import FileSystemStorage
from django.contrib.auth import logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required

from .models import *
from .forms import *
from django.contrib.auth.models import User


# if user is signed in and has access to phone gps, show driver users on map if not driver
# if driver user is signed in, shows nothing on map until a non-driver requests a pickup
# if user is signed in but doesn't have location available, give option to look at map but not interact with users
# go to login page if not logged in
@login_required
def index(request):
    # set sessions
    user = request.user
    request.session['id'] = user.id
    info = user.userinfo_set.all().first()
    request.session['isdriver'] = info.is_driver
    # get all Users to display on the map
    info = User.objects.all()
    return render(request,"map/index.html", {'info': info})


# update the current users coordinates from the google map api
# updates every 40 seconds while on index
@login_required
def update_coords(request):
    # update coordinate values for the user by the cookie data
    curUser = get_object_or_404(User, pk=request.session['id'])
    curInfo = curUser.userinfo_set.all().first()
    # use default coordinates for abbotsford if nothing in cookie key
    curInfo.cur_lat = request.COOKIES.get('lat', '49.0504')
    curInfo.cur_long = request.COOKIES.get('long', '-122.285042')
    curInfo.save()
    # redirect back to index to show map
    return redirect(reverse('map:index'))


# sets the driver_id for the non-driver user that requests a pickup to the id of the driver they want
# uses this to display the users that want a pickup to the driver
@login_required
def book(request, user_id):
    # only allow if not driver
    if not request.session['isdriver']:
        # set the id for the driver that the user wants to be picked up by
        curUser = get_object_or_404(User, pk=request.session['id'])
        curInfo = curUser.userinfo_set.all().first()
        curInfo.driver_id = user_id
        curInfo.save()
        # set the session to track the driver to be booked to for use in user pickup completion
        request.session['driverid'] = user_id
    # redirect back to index to show map
    return redirect(reverse('map:index'))


# allows the requester to complete their pickup, resetting their driver_id for tracking the pickup driver to 0
# doing this removes them from the driver's map, indicating that their pickup is complete
@login_required
def complete(request):
    # reset the id for the driver that the user wants to be picked up by
    curUser = get_object_or_404(User, pk=request.session['id'])
    curInfo = curUser.userinfo_set.all().first()
    curInfo.driver_id = 0
    curInfo.save()
    # set the session to track the driver to be booked to 0
    request.session['driverid'] = 0
    # redirect back to index to show map
    return redirect(reverse('map:index'))


# displays the user profile depending on the user_id in the url
# also handles form posts from the profile page for users updating their information and other users submitting reviews on the page
def profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    # get user info to send to template
    info = user.userinfo_set.all().first()

    # if form is posted, either update user information or create review
    if request.method == 'POST':
        # update database from update form
        if 'Update' in request.POST:
            # updates info only if something was entered in the field
            if request.POST.get("username") != "": user.username = request.POST.get("username")
            if request.POST.get("email") != "": user.email = request.POST.get("email")
            if request.POST.get("password1") != "": user.set_password(request.POST.get("password1"))
            if request.POST.get("bio") != "": info.bio = request.POST.get("bio")
            # save the uploaded profile pic file if a file is uploaded
            if len(request.FILES) != 0 and request.FILES['profpic'].size != 0:
                pic = request.FILES['profpic']
                info.image = pic
            # save both the changed user and info for that user
            user.save()
            info.save()
            # update session in case of password change
            update_session_auth_hash(request, user)

        # write new review from review form
        elif 'Review' in request.POST:
            # get the author for the review as the one issuing the request
            author = get_object_or_404(User, pk=request.session['id'])
            user.review_set.create(author=str(author), rating=request.POST.get('rating'), review_text=request.POST.get('revtext'))
            user.save()

        # go back to profile page after updates to it
        return HttpResponseRedirect(reverse('map:profile', args=(user.id,)))

    return render(request, 'map/profile.html', {'user': user, 'info': info})


# displays the register form on the register page and handles user creation on if form is posted
def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        # if the form is valid, use the information from it to create a new user and userinfo for that user
        if form.is_valid():
            email = form.cleaned_data['email']
            user_name = form.cleaned_data['user_name']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            is_driver = form.cleaned_data['is_driver']
            password = form.cleaned_data['password']
            user = User.objects.create_user(username=user_name, password=password, email=email, first_name=first_name, last_name=last_name)
            user.save()
            # create the userinfo for the newly created user
            uinfo = user.userinfo_set.create(is_driver=is_driver)
            # set image to default user image
            uinfo.image.name = 'no-img.jpg'
            uinfo.save()
            return HttpResponseRedirect(reverse('map:index'))
        # reshow form with errors if not valid
        else:
            errors = form.errors
            form = SignUpForm()
            return render(request, 'map/register.html', {'form': form, 'errors': errors})
    else:
        form = SignUpForm()
        return render(request, 'map/register.html', {'form': form})


# logs out of the current session and resets the user's driver_id to prevent from being tracked by drivers even on logout
def logout_view(request):
    # set the driver_id for the current user to 0 when logging off, so drivers dont keep users that never press compete pickup
    curUser = get_object_or_404(User, pk=request.session['id'])
    curInfo = curUser.userinfo_set.all().first()
    curInfo.driver_id = 0
    curInfo.save()

    logout(request)
    return redirect(reverse(settings.LOGIN_URL))

driver_app/map/templates/map/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" href="{% static 'map/style.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <title>Driver App</title>

  <style>
/* superuser is this : username:  batman pass: test0987

  /*
  Map settings*/
  #map {
    height: 575px;
    width: 90%;
    margin: auto;
  }

  </style>
</head>
<body id="index">

  <!-- Logout button if user is logged in -->
  {% if user.is_authenticated %}
  <a id="inlog" href="{% url 'map:logout' %}">LOGOUT</a>
  {% endif %}

  <div style="margin-left:120px; margin-top:10px; margin-bottom:5px;" id="floating-panel">
    <input id="address" type="textbox" value="Sydney, NSW">
    <input id="submit" type="button" value="Geocode">
  </div>
  <div id="map"> </div>


  <script type="text/JavaScript">


	var map;

	function initMap(){
		var Newinfowindow = new google.maps.InfoWindow();
		var newmarker;
		var infowindow = new google.maps.InfoWindow();

		//get random number for coords
		function genRand(min, max, decimalPlaces) {
			var rand = Math.random()*(max-min) + min;
			var power = Math.pow(10, decimalPlaces);
			return Math.floor(rand*power) / power;
		}

		var infoWindow = new google.maps.InfoWindow({
			content: "hi"
		});
	    
		//infoWindow for driver

		//sample coords
		var myLatLng = {lat: 49.029089 , lng: -122.285471};
		//lat: 49.029089 , lng: -122.285471

		//map display options
		var options = {
			zoom: 15,
			center: {lat:49.0504, lng: -122.3045}
		}
		
		// new map
		var map = new google.maps.Map(document.getElementById('map'), options);

		//Array of markers
		var markers = [
		{
			//  coords:{lat:49.029053,lng: -122.285431},
			iconImage:'http://maps.google.com/mapfiles/kml/shapes/cabs.png',
			content:'<h1>Driver One</h1>'
		},
		];

		//loop through markers to call them one at a time
		for(var i=0; i<markers.length; i++){
			addMarker(markers[i]);
		}

		//function 'addMarker' that passes in values instead of hard coding
		//dynamic coords e.g.
		//addMarker function
		function addMarker(props){
			var marker = new google.maps.Marker({
				//passes in coords
				position:props.coords,
				map:map,
				//change the icons/Marker
				//icon: props.iconImage
			});
			//check for customicon

			//check if content put inspect
			if(props.content){
			//info box for hovering icon
			}

			//listen for infoWindow
			//event listener
			marker.addListener('click', function(){ //listen for click / function runs when it happens
				infoWindow.open(map, marker);
			});

		}

		if (navigator.geolocation) {
			navigator.geolocation.getCurrentPosition(function(position) {
				var pos = {
					lat: position.coords.latitude,
					lng: position.coords.longitude
				};
				
				// set the cookies for coordinates
				document.cookie = "lat=" + position.coords.latitude;
				document.cookie = "long=" + position.coords.longitude;
					
				// user at geolocation
				newmarker = new google.maps.Marker({
					position: pos,
					map:map,
					content: '',
					title: '{{ user.username }}',
					icon: personImage
				});
				
				google.maps.event.addListener(newmarker, 'click', (function(newmarker){
					return function(){
						// set content to show username and link to their profile
						infowindow.setContent("<a href='{% url 'map:profile' user.id %}'><b>{{ user.username }}</b></a>");
						infowindow.open(map, newmarker);
					}
				})(newmarker));
				
				map.setCenter(pos);
				map.setZoom(11);
				
				
				
				// only show markers if person using app is not a driver
				{% if not request.session.isdriver %}
				
				{% for user in info %}
				{% with uinfo=user.userinfo_set.all|first %}
				
				// only show users on map that are drivers
				{% if uinfo.is_driver is True %}

				// show drivers on map that are logged in
				{% if user.is_authenticated %}
		
				var position = new google.maps.LatLng({{ uinfo.cur_lat }}, {{ uinfo.cur_long }});
				
				newmarker = new google.maps.Marker({
					position: position,
					map:map,
					content: '{{ user.email }}',
					title: '{{ user.username }}',
					icon: carImage
				});

				google.maps.event.addListener(newmarker, 'click', (function(newmarker){
					return function(){
						// set content to show username and link to their profile
						infowindow.setContent("<a href='{% url 'map:profile' user.id %}'><b>{{ user.username }}</b></a>");
						infowindow.open(map, newmarker);
					}
				})(newmarker));
				
				// THIS RANDOMLY PLACES ALL DRIVER USERS IN THE DATABASE THAT ARENT LOGGED IN ON THE MAP AS AN EXAMPLE
				// IN REAL PRODUCTION, THIS WOULD BE DELETED SO IF DRIVERS ARENT LOGGED IN THEY DONT SHOW ON MAP
				{% else %}
				
				var position = new google.maps.LatLng(pos.lat + genRand(.001,.009, 4), pos.lng-genRand(.002,.009, 4));
				
				newmarker = new google.maps.Marker({
					position: position,
					map:map,
					content: '{{ user.email }}',
					title: '{{ user.username }}',
					icon: carImage
				});

				google.maps.event.addListener(newmarker, 'click', (function(newmarker){
					return function(){
						// set content to show username and link to their profile
						infowindow.setContent("<a href='{% url 'map:profile' user.id %}'><b>{{ user.username }}</b></a>");
						infowindow.open(map, newmarker);
					}
				})(newmarker));

				{% endif %}
				{% endif %}
				{% endwith %}
				{% endfor %}
				
				// only show drivers the users that want to be picked up on map
				{% else %}
				
				{% for user in info %}
				{% with uinfo=user.userinfo_set.all|first %}
				
				// only show users on map that aren't drivers and want to picked up by the driver and are logged in
				{% if uinfo.is_driver is False and uinfo.driver_id == request.session.id and user.is_authenticated %}
				
				var position = new google.maps.LatLng({{ uinfo.cur_lat }}, {{ uinfo.cur_long }});
				
				newmarker = new google.maps.Marker({
					position: position,
					map:map,
					content: '',
					title: '{{ user.username }}',
					icon: personImage
				});

				
				// set content to show username and link to their profile
				infowindow.setContent("<a href='{% url 'map:profile' user.id %}'><b>{{ user.username }}</b></a><br><b>{{ user.first_name }} has requested a pickup!</b>");
				infowindow.open(map, newmarker);
				
				
				{% endif %}
				{% endwith %}
				{% endfor %}
				{% endif %}
			
			}, function() {
				handleLocationError(true, infoWindow, map.getCenter());
			});
		} else {
			// Browser doesn't support Geolocation
			handleLocationError(false, infoWindow, map.getCenter());
		}

		function handleLocationError(browserHasGeolocation, infoWindow, pos) {
			infoWindow.setPosition(pos);
			infoWindow.setContent(browserHasGeolocation ?
			'Error: The Geolocation service failed.' :
			'Error: Your browser doesn\'t support geolocation.');
			infoWindow.open(map);
		}

		var carImage = {
			url: 'https://static.thenounproject.com/png/331565-200.png',
			scaledSize: new google.maps.Size(50, 50),
			origin: new google.maps.Point(0,0),
			anchor: new google.maps.Point(0, 0)
		}
		
		var personImage = {
			url: 'https://static.thenounproject.com/png/331569-200.png',
			scaledSize: new google.maps.Size(50, 50),
			origin: new google.maps.Point(0,0),
			anchor: new google.maps.Point(0, 0)
		}
		
	}
	
	// update coordinates for users every 40 seconds
	setTimeout(function(){ window.location.href = "{% url 'map:update_coords' %}"; }, 40000);
	
</script>

<script async defer src="//maps.googleapis.com/maps/api/js?key=AIzaSyCNKF-8h5htY6WIGg5czAuhYodWEE8pU3w&callback=initMap"></script>
</body>
</html>

driver_app/map/templates/map/profile.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="profile" content="User Profile">
		
        <title>Driver App Profile</title>
		
		<!-- Mobile Specific Meta
		================================================== -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
		
		<!--
		Google Font
		=========================== -->   
		<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
		<!-- Font Awesome Symbols -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		
		<!-- CSS
		================================================== -->
		<link rel="stylesheet" type="text/css" href="{% static 'map/style.css' %}">
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
		<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<!-- Latest compiled JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		
		<!-- Validate form -->
		<script type="text/javascript">
			function validate(form){
				fail = valEmail(form.email.value);
				fail += valPass(form.password1.value, form.password2.value);
				if (fail == "") 
					return true;
				else { 
					alert(fail); 
					return false;
				}
			}
			
			// for browsers not supporting input type email
			// ensure email formatted properly with at least an @ and . symbol
			function valEmail(val){
				// if nothing entered, still valid
				if (val == "") return "";
				if (!(/[@]/.test(val))) {
					return "Emails must contain the '@' symbol.\n";
				}
				if (!(/[.]/.test(val))){
					return "Emails must specify the domain.\n";
				}
				return "";
			}
			
			// ensure password contains at least 1 special character, 1 capital and lower case, and 1 number and is over 6 characters
			function valPass(val1, val2){
				// if nothing entered, still valid
				if (val1 == "" && val2 == "") return "";
				if (!(/[!@#$%]/.test(val1))){
					return "Passwords must have at least 1 special character of !, @, #, $, or %.\n";
				}
				if (!(/[a-z]/.test(val1))){
					return "Passwords must have at least 1 lower case letter.\n";
				}
				if (!(/[A-Z]/.test(val1))){
					return "Passwords must have at least 1 upper case letter.\n";
				}
				if (!(/[0-9]/.test(val1))){
					return "Passwords must have at least 1 number.\n";
				}
				if (val1.length < 7){
					return "Passwords must be over 6 characters in length.\n";
				}
				if (val1 !== val2){
					return "Passwords must match in both fields.\n"
				}
				return "";
			}
			
		</script>
	
    </head>
	
    <body id="profile">
	    
		<div class="container-fluid">
			<div class="row">
				<a href="{% url 'map:index' %}"><i class="fa fa-times fa-3x" style="font-size:60px;color:red;"></i></a>
				<!-- Logout button if user is logged in -->
				{% if user.is_authenticated %}
				<a class="logout" href="{% url 'map:logout' %}">LOGOUT</a>
				{% endif %}
				<div id="left" class="col-sm-3 col-xs-12 text-center">
					<!-- User Information -->
					<img alt="Profile Picture" src="{{ info.image.url }}" width="200" height="200">
					<h2>{{ user.username }}</h2>
					<h3>{{ user.first_name }}</h3>
					<h3>{{ user.last_name }}</h3>
					<!-- if on own profile, allow for changing changing info --> 
					{% if request.session.id == user.id %}
					<p style="margin-top:25px;" class="bigger"><u>Change Information</u></p>
					<form action="{% url 'map:profile' user.id %}" method="post" enctype="multipart/form-data" onsubmit="return validate(this)">
						{% csrf_token %}
						<p class="bigger">New Profile Picture</p>
						<input style="margin:auto;" type="file" name="profpic"><br>
						<input type="text" name="username" placeholder="New Username" maxlength="50"><br>
						<input type="text" name="email" placeholder="New Email" maxlength="200"><br>
						<p class="bigger">Change Password</p>
						<input type="password" name="password1" placeholder="New Password" maxlength="50"><br>
						<input type="password" name="password2" placeholder="Reenter Password" maxlength="50"><br>
						<p class="bigger">Change Bio</p>
						<textarea name="bio" rows="20" cols="20" maxlength="1000"></textarea>
						<br>
						<input type="submit" name="Update" value="Update">
					</form>
					{% endif %}
					
				</div>
				<div id="right" class="col-sm-9 col-xs-12">
					<div style="text-align:center;margin-top:70px;">
						<!-- Complete the pickup for this driver if they've been requested -->
						{% if info.is_driver and request.session.id != user.id and request.session.driverid == user.id %}
						<a href="{% url 'map:complete' %}" id="book" >Complete Pickup!</a>
						<p>Make sure to leave a review first!</p>
						<!-- Request for pickup if not on own account and is driver -->
						{% elif info.is_driver and request.session.id != user.id %}
						<a href="{% url 'map:book' user.id %}" id="book" >Request Pickup!</a>
						{% endif %}
					</div>
					<!-- Show user bio if they have one -->
					<div class="container" id="bio">
						<p>{{ info.bio }}</p>
					</div>
					
					<h2 class="text-center">Reviews</h2>
					<!-- Loop over reviews for this user and display them -->
					{% for review in user.review_set.all %}
						<h4 class="review-text">{{review.author}}</h3>
						<p class="review-text">rating: {{review.rating}}</p>
						<p class="review-text">{{review.review_text}}</p>
					{% endfor %}
					
					<!-- section to write review -->
					<!-- Don't allow to write review on own account	-->
					{% if request.session.id != user.id %}
					<h3>Write a Review</h3>
					<hr>
					<form action="{% url 'map:profile' user.id %}" method="post" >
						{% csrf_token %}
						<textarea name="revtext" style="margin-top: 5px;" rows="10" cols="60" maxlength="500" required ></textarea>
						<br>
						<label>  
                            Rating:                         
                            <input type="radio" name="rating" value="1" required >1
                            <input type="radio" name="rating" value="2" required >2
							<input type="radio" name="rating" value="3" required >3
							<input type="radio" name="rating" value="4" required >4
							<input type="radio" name="rating" value="5" required >5
						</label> 
						<input type="submit" name="Review" value="Review" >
					</form>
					{% endif %}
					
				</div>
			</div>
		</div>
        
		
		<!-- end Footer Area
		========================================== -->
		
		<!-- 
		Essential Scripts
		=====================================-->
		
		<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<!-- Latest compiled JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		

    </body>
</html>

driver_app/map/templates/map/register.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="profile" content="User Profile">
		
        <title>Sign Up</title>
		
		<!-- Mobile Specific Meta
		================================================== -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
		
		<!--
		Google Font
		=========================== -->   
		<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
		
		<!-- CSS
		================================================== -->
		<link rel="stylesheet" type="text/css" href="{% static 'map/style.css' %}">
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
		<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<!-- Latest compiled JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		
	
    </head>
	
    <body id="register">
	    
		<h1>Sign Up</h1>
		<div class="container-fluid">
			<!-- Show errors in fields if there are any -->
			{% if errors %}
				{% for key, value in errors.items %}
					<p class="errormsg">{{ value }}</p>
				{% endfor %}
			{% endif %}
			<!-- action kept blank since same view for the url is both serving form and getting post -->
			<form action="" method="post">
				{% csrf_token %}
				{{ form }}
				<br>
				<input id="regsub" type="submit" value="Submit">
			</form>
		</div>
        
		
		<!-- end Footer Area
		========================================== -->
		
		<!-- 
		Essential Scripts
		=====================================-->
		
		<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<!-- Latest compiled JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		

    </body>
</html>